# This workflow will build a Docker container, publish it to Docker Hub, and deploy it to CSC Cloud Kubernetes when there is a push to the "main" branch.

name: Build and Deploy to CSC Cloud

on:
  push:
    branches: [ "main" ]

env:
  REPO: ${{ github.repository }}
  SHA: ${{ github.sha }}
  DEPLOY: ${{ secrets.K8S_DEPLOYMENT }}

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx # Required for docker/build-push-action
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push the Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: $REPO:$SHA 

    - name: Update Kubernetes deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.K8S_HOST }}
        username: ${{ secrets.K8S_USERNAME }}
        password: ${{ secrets.K8S_PASSWORD }}
        script: kubectl set image deployment $DEPLOY $DEPLOY=$REPO:$SHA
